### ISSUE TITLE
Class Diagram: Java null pointer when cliking two times on a generalization

### ISSUE THREAD

**Issue by fbats** [ObeoNetwork/UML-Designer#665] opened 2015-05-05 12:18 UTC
When cliking two times on a generalization relationship a java null pointer appear in console in debug mode.
Steps: 
- in a class diagram create Two classes and a Generalization between classes.
- click on the generalization a firt time to select it.
- click a second time on the same element. (as if we try to direct edit the element)
  the same error seem to be reproduce for all connection wihtout label (interface realization, ...)

Stack trace: 

!ENTRY org.eclipse.ui 4 0 2015-05-05 14:13:18.587
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
    at org.eclipse.sirius.diagram.ui.internal.edit.parts.AbstractGeneratedDiagramNameEditPart.performDirectEdit(AbstractGeneratedDiagramNameEditPart.java:279)
    at org.eclipse.sirius.diagram.ui.internal.edit.parts.AbstractGeneratedDiagramNameEditPart$2.run(AbstractGeneratedDiagramNameEditPart.java:310)
    at org.eclipse.emf.transaction.impl.TransactionalEditingDomainImpl.runExclusive(TransactionalEditingDomainImpl.java:328)
    at org.eclipse.sirius.diagram.ui.internal.edit.parts.AbstractGeneratedDiagramNameEditPart.performDirectEditRequest(AbstractGeneratedDiagramNameEditPart.java:301)
    at org.eclipse.sirius.diagram.ui.edit.api.part.AbstractDiagramNameEditPart.performRequest(AbstractDiagramNameEditPart.java:288)
    at org.eclipse.gmf.runtime.diagram.ui.editparts.ConnectionEditPart.performDirectEditRequest(ConnectionEditPart.java:1500)
    at org.eclipse.sirius.diagram.ui.edit.api.part.AbstractDiagramEdgeEditPart.performRequest(AbstractDiagramEdgeEditPart.java:868)
    at org.eclipse.gef.tools.DelayedDirectEditHelper.run(DelayedDirectEditHelper.java:108)
    at org.eclipse.swt.widgets.Display.runTimer(Display.java:4273)
    at org.eclipse.swt.widgets.Display.messageProc(Display.java:3360)
    at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
    at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2549)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

**Comment by mbats** [comment] 2017-01-26 13:09
The previous fix provides a workaround by adding a DirectEditTool for mappings
with no label expression.
This should be removed when
https://bugs.eclipse.org/bugs/show_bug.cgi?id=511036 will be fixed.

**Comment by AxelRICHARD** [comment] 2017-03-22 10:23
The bug seems to be fix with the latest version of Sirius and UML Designer (see investigation on https://bugs.eclipse.org/bugs/show_bug.cgi?id=511036). So I close the bug. Feel free to reopen it if the problem is still there.

**Closed by AxelRICHARD** 2017-03-22 10:23 UTC
Labels: Class diagram, Waiting for other product
