### ISSUE TITLE
"Line Style: Tree Style Routing" shouldn't turn a corner when it only connects two classes in  Class Diagram

### ISSUE THREAD

**Issue by vegetable09** [ObeoNetwork/UML-Designer#831] opened 2016-04-04 07:45 UTC

**Comment by AxelRICHARD** [comment] 2017-02-23 09:40
Hello,

I'm not able to reproduce your problem. Can you give us a test case please ?

**Comment by mbats** [comment] 2017-07-19 09:34
We have not enough information to reproduce, I close the issue, if you encounter the problem do not hesitate to reopen this issue by adding a case for reproduction.

**Closed by mbats** 2017-07-19 09:34 UTC
Labels: Class diagram
