### ISSUE TITLE
Class diagram modal dialogs are canceled when enter is pressed

### ISSUE THREAD

**Issue by sarod** [ObeoNetwork/UML-Designer#819] opened 2016-03-03 13:00 UTC
When double clicking an element in the class diagram it opens a modal dialog. (Class or Package for instance)
After changing something in the modal dialog when I press enter the dialog close but changes are canceled instead of being applied.

**Comment by mbats** [comment] 2016-03-21 16:20
Please can you send us a screenshot of the problem as we cannot reproduce ?

**Comment by AxelRICHARD** [comment] 2017-02-21 16:55
I succeed to reproduce the problem, it arises when you change the value of a text field and directly press 'enter' key.
The new value of the text field is only taking into account when the focus of the text field is gained or lost. The new value should also be taking into account when the 'enter' key is pressed but it is not the case.
The problem comes from EEF 1.5 and not from UML Designer.
UML Designer has planned to move to EEF 2.0, so the problem will be automatically fix when EEF 2.0 will be used by UML Designer.

**Comment by mbats** [comment] 2017-07-19 16:36
Fixed by #844

**Closed by mbats** 2017-07-19 16:36 UTC
Labels: Class diagram
